/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _Q_H_RPCGEN
#define _Q_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef double *PDouble;

typedef int *PInt;

#define Q 0x20000001
#define VQ 1

#if defined(__STDC__) || defined(__cplusplus)
#define f 1
extern  PDouble * f_1(PInt , CLIENT *);
extern  PDouble * f_1_svc(PInt , struct svc_req *);
extern int q_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define f 1
extern  PDouble * f_1();
extern  PDouble * f_1_svc();
extern int q_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_PDouble (XDR *, PDouble*);
extern  bool_t xdr_PInt (XDR *, PInt*);

#else /* K&R C */
extern bool_t xdr_PDouble ();
extern bool_t xdr_PInt ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_Q_H_RPCGEN */
