/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "q.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

PDouble *
f_1(PInt arg1,  CLIENT *clnt)
{
	static PDouble clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, f,
		(xdrproc_t) xdr_PInt, (caddr_t) &arg1,
		(xdrproc_t) xdr_PDouble, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
