/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "q.h"


void
q_1(char *host)
{
	CLIENT *clnt;
	PDouble  *result_1;
	PInt f_1_arg1;
	/* código adicionado */
	static int i;
	i = 47;
	f_1_arg1 = &i;
	
#ifndef	DEBUG
	clnt = clnt_create (host, Q, VQ, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = f_1(f_1_arg1, clnt);
	if (result_1 == (PDouble *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("llega %f \n", **result_1); /* agregado */
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	q_1 (host);
exit (0);
}
