/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "q.h"

PDouble *
f_1_svc(PInt arg1,  struct svc_req *rqstp)
{
	static PDouble  result;

	/* inserted server code here */
	static double d;
	d = *arg1;
	d += 0.5;
	result = &d;

	return &result;
}
